# wrangler.toml
name = "myapp" # Replace with your actual project name if desired
compatibility_date = "2024-09-23" # Updated compatibility date as suggested by error

# Pages build output directory
pages_build_output_dir = "dist"

# Node.js compatibility flag for Pages Functions
compatibility_flags = [ "nodejs_compat" ]

# Add other configurations if needed
# [vars]
# MY_VAR = "value"
